### ISSUE TITLE
Option to interpret variables using cftime

### ISSUE THREAD

**Issue by TomNicholas** [zarr-developers/VirtualiZarr#117]
https://github.com/TomNicholas/VirtualiZarr/issues/68#issuecomment-2113983642 explains how we don't currently have support for virtualizing encoded time variables. 

To handle this it looks like we need to an another option to `open_virtual_dataset`, a `cftime_vars` kwarg, which specifies which variables should be interpreted using cftime. (I think `cftime_vars` should be a subset of `loadable_vars`.) This suggestion comes from how kerchunk deals with this problem:

https://fsspec.github.io/kerchunk/reference.html#kerchunk.combine.MultiZarrToZarr

```
”cf:{var}”, interpret the value of var using cftime, returning a datetime. 
These will be automatically re-encoded with cftime, unless you specify an “M8[*]” 
dtype for the coordinate, in which case a conversion will be attempted.
```

_Originally posted by @dcherian in https://github.com/TomNicholas/VirtualiZarr/issues/73#issuecomment-2047989180_

**Comment by jsignell** [comment]
Just to say that I am taking a look at this.

**Comment by jbusecke** [comment]
Just wanted to add +1 here, since this is quite important for our work to bring virtual zarr access to ESGF (https://github.com/jbusecke/esgf-virtual-zarr-data-access/issues/8). Please let me know if/where I could help test, and ill try to make some time.

**Comment by jsignell** [comment]
This is still on my radar and I appreciate the nudge. The test is the one thing that I am confident in 😅 it's more the implementation that needs some thought.

**Comment by TomNicholas** [comment]
It's possible the proper way to implement this is actually to use [`xarray.decode_cf`](https://github.com/pydata/xarray/blob/56209bd9a3192e4f1e82c21e5ffcf4c3bacaaae3/xarray/conventions.py#L288), which eventually sends variables through these very-relevant-looking `CFDateTimeCoder` decoding methods

https://github.com/pydata/xarray/blob/56209bd9a3192e4f1e82c21e5ffcf4c3bacaaae3/xarray/conventions.py#L288
