### ISSUE TITLE
Publish as a package

### ISSUE THREAD

**Issue by TomNicholas** [zarr-developers/VirtualiZarr#13]
On pip and conda-forge.

Obviously needs to actually work first #2

**Comment by TomNicholas** [comment]
@maxrjones FYI I just hit release on this

**Comment by TomNicholas** [comment]
But it did not work 😅 

https://github.com/zarr-developers/VirtualiZarr/actions/runs/9554118828

**Comment by maxrjones** [comment]
yikes, sorry! I need to run for a family obligation but will take a look later this evening.

**Comment by TomNicholas** [comment]
No rush!! Just making sure you had seen it.

**Comment by maxrjones** [comment]
I did not, so thanks!

Just at a quick look, the actions include `Successfully built virtualizarr-0.1.0+unknown.tar.gz and virtualizarr-0.1.0+unknown-py3-none-any.whl`. We want the package name to be `virtualizarr-0.1.0`, not `virtualizarr-0.1.0+unknown`, so I think the workflow may have actually worked properly in not uploading the package. There may be a change needed in pyproject.toml

**Comment by TomNicholas** [comment]
v1.0.0 is successfully up on PyPI, the only left here is to also put it on conda-forge

**Comment by TomNicholas** [comment]
It's up on conda-forge now too https://anaconda.org/conda-forge/virtualizarr
