### ISSUE TITLE
HDF5 error on main

### ISSUE THREAD

**Issue by TomNicholas** [zarr-developers/VirtualiZarr#147]
We've started getting an error on `main` ([link](https://github.com/zarr-developers/VirtualiZarr/actions/runs/9559364935/job/26349624374)):

```
FAILED virtualizarr/tests/test_xarray.py::TestLoadVirtualDataset::test_loadable_variables - RuntimeError: Unspecified error in H5DSget_num_scales (return value <0)
```

**Comment by TomNicholas** [comment]
The error actually comes from where we call `xr.open_dataset`, which uses `h5netcdf` then `h5py`. That's quite surprising - we're using the latest version of xarray which seems to have no issues on that repo.

I'm also confused why all my tests pass locally when I have the same versions of `xarray==2024.6.0`, `h5netcdf==1.3.0` and `h5py==3.11.0` installed as [the CI run](https://github.com/zarr-developers/VirtualiZarr/actions/runs/9559364935/job/26349624582#step:4:227) does. (Though I can't seem to find what version of `hdf5` the CI run installed - I have `1.14.3` locally.)

**Comment by maxrjones** [comment]
@TomNicholas I'm going to open a PR to debug this if that's alright to you. I think it's related to the hdf5 libraries not being compiled since we're only using PyPI in the CI.
