### ISSUE TITLE
Automatically run pre-commit on all PRs

### ISSUE THREAD

**Issue by TomNicholas** [zarr-developers/VirtualiZarr#180]
#179 managed to get merged without passing pre-commit's linting checks (linting re-applied in  https://github.com/zarr-developers/VirtualiZarr/commit/47303fa0df8f71dead57bbfc48a6f2db4aee6cba). It would be better to run pre-commit on every PR and either loudly fail or automatically push commits to that branch, like xarray does.

**Comment by norlandrhagen** [comment]
Looks like the [pre-commit CI Github app](https://pre-commit.ci/) was missing. I added it to the repo.

**Comment by norlandrhagen** [comment]
This should now be fixed! This [PR](https://github.com/zarr-developers/VirtualiZarr/pull/211) shows the .pre-commit CI action working.
