### ISSUE TITLE
Support for numpy<2?

### ISSUE THREAD

**Issue by maresb** [zarr-developers/VirtualiZarr#184]
I'm really excited about this project, but it's currently pretty difficult to install in any non-minimal environment because Numpy 2.0 is so recent. How essential is your use of 2.0 features? Is there any chance of this being relaxed?

**Comment by TomNicholas** [comment]
Hey! We're using numpy 2.0 for the new variable-length string dtype, as a good way to efficiently store arrays of paths to files.

Context here:

https://github.com/zarr-developers/VirtualiZarr/issues/33

https://github.com/zarr-developers/VirtualiZarr/pull/107#discussion_r1637241715

If you really want backwards-compatibility we can accept a PR that generalizes this, but its always going to be less efficient to use a fixed-length string dtype.

**Comment by maresb** [comment]
Thanks a lot for the explanation! Relying on a new dtype seems like fairly essential use of 2.0, and it'd probably be a significant amount of work to maintain a parallel backwards-compatible implementation.

I tracked down one of my current bottlenecks which is `xagg`→`pytables`→`numpy<2`, and happily that's being [actively worked on](https://github.com/PyTables/PyTables/pull/1183) :rocket:!

I think my current strategy will be to build a separate container for the kerchunking step of my pipeline so that I can make use of VirtualiZarr until numpy 2 is widely supported.

Thanks so much for the quick response, it's really helpful!

**Comment by TomNicholas** [comment]
Sounds good! Let us know how you get on using VirtualiZarr.

**Comment by maresb** [comment]
With the PyTables release just now, there are no more dependency constraints blocking me from upgrading to NumPy 2 and using VirtualiZarr in my main environment. :rocket:
