### ISSUE TITLE
Scalars, when concatenating, gain concat dimension

### ISSUE THREAD

**Issue by kthyng** [zarr-developers/VirtualiZarr#185]
I have a bunch of model output files I would like to read in and then concatenate together. However, those files come with many scalars and I am finding those scalars gain the time dimensions when they are concatenated together. Here is an example:

```
from virtualizarr import open_virtual_dataset

vds = open_virtual_dataset('air.nc')
ds1 = ds.isel(time=slice(None, 1460))
ds2 = ds.isel(time=slice(1460, None))

ds1["theta"] = 5
ds2["theta"] = 5

ds1.to_netcdf('air1.nc')
ds2.to_netcdf('air2.nc')

vds1 = open_virtual_dataset('air1.nc', indexes={})
vds2 = open_virtual_dataset('air2.nc', indexes={})

combined_vds = xr.combine_nested([vds1, vds2], concat_dim=['time'], coords='minimal', compat='override')

```

Now `combined_vds.theta` has a time dimension.

Is there an easy way to avoid this? Thank you!

**Comment by TomNicholas** [comment]
This is just the normal behavior of xarray.concat. You should be able to avoid it by passing dada_vars='minimal'. We should probably update the docs examples with that change too.

**Comment by kthyng** [comment]
Oh I see! Sure, everything is just like in xarray... ok. Thanks.

**Comment by TomNicholas** [comment]
It should be yes! If it's not then that's a bug.

See also https://github.com/pydata/xarray/issues/8778 for improving the default arguments to concat/combine.
