### ISSUE TITLE
Why do I have to manually approve workflow CI on every PR?

### ISSUE THREAD

**Issue by TomNicholas** [zarr-developers/VirtualiZarr#190]
Every time someone who doesn't have push access to this repo submits a PR github asks me to manually approve the workflow to run the CI tests on their PR branch. I would rather it just ran them all automatically (like xarray does).

cc @maxrjones @norlandrhagen in case either of you know what I need to change

**Comment by TomAugspurger** [comment]
At https://github.com/zarr-developers/VirtualiZarr/settings/actions admins can configure the requirements.

![image](https://github.com/user-attachments/assets/c1e16135-992f-4c88-97ec-4ba3894623a2)

**Comment by norlandrhagen** [comment]
Looks like this was updated, so closing.
