### ISSUE TITLE
open_virtual_dataset HTTPS access fails

### ISSUE THREAD

**Issue by ayushnag** [zarr-developers/VirtualiZarr#195]
Currently `open_virtual_dataset` cannot open a dataset when given a public HTTPS url. This happens because [`reader_options` is set on this line](https://github.com/zarr-developers/VirtualiZarr/blob/5d0851976778ebaf52eb6df57970b0706a892d98/virtualizarr/xarray.py#L128) to s3-like syntax which probably messes up the https request. The functionality is correct in `_fsspec_openfile_from_filepath` so it's a pretty simple fix to just update the linked line in `xarray.py`

Also noticed by @kthyng in https://github.com/zarr-developers/VirtualiZarr/pull/186#issuecomment-2231450332

Here is an example:
```python
>>> from virtualizarr import open_virtual_dataset
>>> open_virtual_dataset("https://github.com/pydata/xarray-data/raw/master/ROMS_example.nc", indexes={})
Traceback (most recent call last): ...
FileNotFoundError: https://github.com/pydata/xarray-data/raw/master/ROMS_example.nc
```

```python
>>> import fsspec
>>> z = fsspec.filesystem("https").open("https://github.com/pydata/xarray-data/raw/master/ROMS_example.nc")
>>> z.readline()
>>> b'\x89HDF\r\n'
```

**Comment by kthyng** [comment]
Ah, thanks for noticing!
