### ISSUE TITLE
Issues with mypy / other CI checks

### ISSUE THREAD

**Issue by TomAugspurger** [zarr-developers/VirtualiZarr#209]
I think our static type checking configuration might not be 100% correct.

1. The `mypy` configuration in pyproject.toml at https://github.com/zarr-developers/VirtualiZarr/blob/b34a1ee47572901ed6a3623c97d340157a0fa62a/pyproject.toml#L75 must be under a `tool.mypy` prefix, not `mypy` when you're using pyproject.toml
2. I think that the mypy configuration in `.pre-commit-config.yaml` isn't , at least for my machine. Mine fails with `ERROR: No matching distribution found for types-pkg_resources`. We aren't using pkg-resources, so we shouldn't need that.
3. IMO, it might make sense to move mypy checks out of pre-commit and to a separate check? I think that mypy requires that 3rd party dependencies be installed into the environment so that those boundaries are type checked. Seems wasteful to install all those deps for testing, and then again for type checking.
4. I think that pre-commit isn't being run in CI

I have a branch starting to fix these up.

Expanding on issue 3, on main I have two failures:

```
virtualizarr/zarr.py:98: error: Argument "zarr_format" to "ZArray" has incompatible type "int"; expected "Literal[2, 3]"  [arg-type]
virtualizarr/tests/test_zarr.py:43: error: Argument "filetype" to "open_virtual_dataset" has incompatible type "str"; expected "FileType | None"  [arg-type]
```

On a branch with that moved to my dev env (and a few modules suppressed, since they don't provide type hints), I get more

```
virtualizarr/zarr.py:137: error: Function "virtualizarr.zarr.ZArray.dict" is not valid as a type  [valid-type]
virtualizarr/zarr.py:137: note: Perhaps you need "Callable[...]" or a callback protocol?
virtualizarr/zarr.py:253: error: Unsupported operand types for / ("Path" and "Hashable")  [operator]
virtualizarr/zarr.py:289: error: Argument 1 to "list" has incompatible type "tuple[Hashable, ...]"; expected "Iterable[str]"  [arg-type]
virtualizarr/kerchunk.py:226: error: Argument 2 to "variable_to_kerchunk_arr_refs" has incompatible type "Hashable"; expected "str"  [arg-type]
virtualizarr/kerchunk.py:239: error: Argument 1 to "join" of "str" has incompatible type "list[Hashable]"; expected "Iterable[str]"  [arg-type]
virtualizarr/xarray.py:31: error: Definition of "__array__" in base class "ManifestArray" is incompatible with definition in base class "ExplicitlyIndexed"  [misc]
virtualizarr/xarray.py:162: error: Argument 1 to "open_dataset" has incompatible type "Any | IOBase"; expected "str | PathLike[Any] | BufferedIOBase | AbstractDataStore"  [arg-type]
virtualizarr/xarray.py:196: error: Cannot infer type argument 1 of <dict>  [misc]
virtualizarr/xarray.py:196: note: Try assigning the literal to a variable annotated as dict[<key>, <val>]
virtualizarr/xarray.py:379: error: Incompatible types in assignment (expression has type "IndexVariable", target has type "tuple[Hashable, Any, dict[Any, Any], dict[Any, Any]]")  [assignment]
virtualizarr/xarray.py:383: error: Incompatible types in assignment (expression has type "Variable", target has type "tuple[Hashable, Any, dict[Any, Any], dict[Any, Any]]")  [assignment]
virtualizarr/tests/test_zarr.py:43: error: Argument "filetype" to "open_virtual_dataset" has incompatible type "str"; expected "FileType | None"  [arg-type]
Found 13 errors in 5 files (checked 22 source files)
```

**Comment by cisaacstern** [comment]
Thanks for the work here, Tom. I actually plagiarized (with [credit](https://github.com/wildlife-dynamics/ecoscope-workflows/blob/e596df3d66159e10f0f059a69b422c957cdf3a7b/.pre-commit-config.yaml#L1-L2)) the pre-commit config here for another project, and then started hitting the same `types-pkg_resources` issue as you mention here, so seeing your issue pop up here helped me understand the cause and solution.

> We aren't using pkg-resources, so we shouldn't need that.

Yes, same in my other project 😮‍💨

**Comment by TomAugspurger** [comment]
I think this is all resolved now.
