### ISSUE TITLE
`open_virtual_dataset` error with TEMPO dmr++

### ISSUE THREAD

**Issue by danielfromearth** [zarr-developers/VirtualiZarr#237]
Trying to open a DMR++ file from the Tropospheric Emissions: Monitoring of Pollution (TEMPO) satellite-based air quality instrument results in the following `TypeError`:

```python
result = open_virtual_dataset("https://data.asdc.earthdata.nasa.gov/asdc-prod-protected/TEMPO/TEMPO_NO2_L2_V03/2024.07.25/TEMPO_NO2_L2_V03_20240725T114404Z_S002G06.nc.dmrpp", indexes={}, filetype="dmrpp", reader_options={"storage_options": fs.storage_options})
```
![temp](https://github.com/user-attachments/assets/e6816921-2b9d-482f-b3aa-e768d1328468)

**Comment by ayushnag** [comment]
Thanks for raising this issue @danielfromearth! This dataset has variables and attributes in the root group and the current code doesn't have logic to handle that. There is already have group parsing logic, I just need to add a case for the root group and your use case will be patched soon.

**Comment by danielfromearth** [comment]
Hi @ayushnag, I was away from this for the past month on some personal leave. 
Has there been any progress on this?  And either way, would it help to catch up soon (perhaps via Openscapes) about this?

**Comment by ayushnag** [comment]
Hey @danielfromearth! Yes this fix uncovered quite a few other issues about groups that I have fixed. I will post a PR very soon

**Comment by TomNicholas** [comment]
@ayushnag FYI there's no reason to wait until the PR is fully working before opening it - I like to open half-baked PRs and mark them as draft just so that people can see what's being worked on

**Comment by ayushnag** [comment]
Good idea, I have opened it now!
