### ISSUE TITLE
Make mypy a separate CI job

### ISSUE THREAD

**Issue by TomNicholas** [zarr-developers/VirtualiZarr#253]
The mypy checks are currently part of the same CI jobs that the test suite runs are. It would be better to have the `mypy` test be separate, so that it's easier to see if a PR only "failed" due to mypy rather than due to actual runtime test failures.

cc @norlandrhagen

**Comment by norlandrhagen** [comment]
I can take this one if you haven't started a PR @TomNicholas.

**Comment by TomNicholas** [comment]
That would be great, thanks @norlandrhagen

**Comment by norlandrhagen** [comment]
https://github.com/zarr-developers/VirtualiZarr/pull/254
