### ISSUE TITLE
mypy spontaneously reporting new error

### ISSUE THREAD

**Issue by sharkinsspatial** [zarr-developers/VirtualiZarr#274]
`mypy` has begun reporting a new error without any changes to the underlying code or from what I can tell any changes in the versions of the `mypy` packages installed.

```
virtualizarr/readers/common.py:34: error: Cannot assign to a type  [misc]
virtualizarr/readers/common.py:34: error: Incompatible types in assignment (expression has type "<typing special form>", variable has type "type[DataTree]")  [assignment]
virtualizarr/readers/common.py:37: error: Definition of "__array__" in base class "ManifestArray" is incompatible with definition in base class "ExplicitlyIndexed"  [misc]
```

This error just began appearing in the [Github action](https://github.com/zarr-developers/VirtualiZarr/actions/runs/11509596589/job/32039982955) and I am unable to reproduce it locally.

**Comment by TomNicholas** [comment]
Maybe same as https://github.com/pydata/xarray/issues/9624?
