### ISSUE TITLE
how to transmit reader_options credential to xarray.open_dataset ?

### ISSUE THREAD

**Issue by mdsumner** [zarr-developers/VirtualiZarr#276]
I've created a json concatenation from netcdf files in S3, and then open it with `xarray.open_dataset("combined.json")`, which is fine but the sources aren't set up for actual reading downstream so I see errors like this when attempts to pull actual values: 

```
"sst/16038.0.0.0" failed to fetch target ['s3://bucket/key.nc', 58900, 652770]
```

I understand that the step here had access to the creds, so how do I pass that on to xarray for later use?   

```
open_virtual_dataset('s3://bucket/key.nc',  reader_options={'storage_options': creds})

```

(Not sure if this is a lack of famil with xarray question or ??)  Feel like I'm missing something simple-ish. 

Fwiw the bucket is public, and an example source file is

```
's3://idea-10.7289-v5sq8xb5/www.ncei.noaa.gov/data/sea-surface-temperature-optimum-interpolation/v2.1/access/avhrr/202410/oisst-avhrr-v02r01.20241024_preliminary.nc'

```

endpoint is 'projects.pawsey.org.au', so it really shouldn't need credentials but I could only get it to work with explicit keys, i.e. 

```
## in open_virtual_dataset: 
reader_options={'storage_options': creds}
```

where 

```
aws_credentials = {"endpoint_url": "https://projects.pawsey.org.au", "key": <key>, "secret": <secret>}
```

**Comment by keewis** [comment]
this appears to work:
```python
import virtualizarr

url = "s3://idea-10.7289-v5sq8xb5/www.ncei.noaa.gov/data/sea-surface-temperature-optimum-interpolation/v2.1/access/avhrr/202410/oisst-avhrr-v02r01.20241024_preliminary.nc"
storage_options = {"endpoint_url": "https://projects.pawsey.org.au", "anon": True}
ds = virtualizarr.open_virtual_dataset(
    url,
    indexes={},
    loadable_variables=["time", "lon", "lat", "zlev"],
    reader_options={"storage_options": storage_options},
)
```
(the important part appears to be `anon=True`)

**Comment by mdsumner** [comment]
Oh cool I didn't understand about the anon part, doh 🙏

My other question is about when *xarray* loads the virtualized store from a . json, how does it obtain these reader_options?

**Comment by mdsumner** [comment]
oh!  awesome,  ty so much!!   it's working, this is excellent
