### ISSUE TITLE
Github docs link

### ISSUE THREAD

**Issue by norlandrhagen** [zarr-developers/VirtualiZarr#346]
The [github docs link ](https://virtualizarr.readthedocs.io/en/stable/api.html) goes to the api docs page. Is this intended or should it point to the [main page](https://virtualizarr.readthedocs.io/en/stable/index.html)?

cc @TomNicholas @maxrjones

**Comment by maxrjones** [comment]
IMO main page would be better

**Comment by TomNicholas** [comment]
Yeah that's not intended, thanks for noticing
